vim.opt.termguicolors = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.expandtab = true
vim.opt.ignorecase = true
vim.opt.mouse = 'a'
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.signcolumn = 'yes'
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.laststatus = 3
vim.opt.showtabline = 1
vim.opt.cmdheight = 0
vim.opt.cursorline = true
vim.opt.timeoutlen = 500
vim.opt.shell = 'nu'
vim.g.mapleader = ' '
